### ISSUE TITLE
[RFE] Support arbitrary macros installed into macros.d folder

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#10]
Note, this is slightly rehashed from #5.

Now that debbuild is capable of parsing macros, it should support being able to read arbitrary macros stored in `/usr/lib/debbuild/macros.d` and `/etc/debbuild` written as `macros.<macroname>`.

Typically, user-specified macros go into `/etc/debbuild`, while macros provided by packages would be in `/usr/lib/debbuild/macros.d`.

For example, your TeXLive and system utilities macros in the `sysmacros` file would be broken up into separate `macros.texlive` and `macros.sysutils`, respectively.

**Comment by ascherer** [comment]
Idea: add the globs `</usr/lib/debbuild/macros.d/macros.*>` and `</etc/debbuild/macros.*>` in `load_conf ()`.

**Comment by ascherer** [comment]
That was as easy as perl.
