### ISSUE TITLE
[RFE] --eval switch for testing macros

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#11]
With RPM, you can locally test for working macros by running `rpm --eval %macro`. If the macro exists, it'll return its values (evaluating the expressions in the macro) to standard output. If it doesn't, it gets returned as is.

For example, here's what a defined macro returns:

```
[~]$ rpm --eval "%make_build"
/usr/bin/make -j4
```

An example of an undefined macro being evaluated:

```
[~]$ rpm --eval "%make"
%make
```

This feature is especially useful once debbuild supports arbitrary macros installed into macros.d folders (see #10).

**Comment by ascherer** [comment]
Idea: new option `eval=s` in `parse_cmd()`; `eval { $ res = expandmacros($opt_value); }`.

**Comment by Conan-Kudo** [comment]
Apparently, this will also be needed if the Open Build Service were to attempt to properly detect the `%_topdir` [like it does for rpm builds](https://github.com/openSUSE/obs-build/blob/5621595beb6cad48bd31a76c7466ec7052e68254/build-recipe-spec#L25) for the debbuild stuff ([it currently assumes `/usr/src/debian`](https://github.com/openSUSE/obs-build/blob/a3c7fab07a0864a402c36fbf7ecd9a998f391938/build-recipe-debbuild#L25)).

**Comment by ascherer** [comment]
let me get up, wash, and have breakfast,  then I'll look into this. :-)

**Comment by ascherer** [comment]
That was even simpler to implement. Note the restriction for `%buildroot`.

**Comment by Conan-Kudo** [comment]
@ascherer Is the restriction why `%make_install` won't print?

**Comment by ascherer** [comment]
`%make_install` contains the macros `%{__make}` (trivial to expand) and `%{?buildroot}`. The latter expands to `%{_buildrootdir}/%{name}-%{version}-%{release}.%{_arch}`, of which only
`%{_buildrootdir}` and `%{_arch}` are known from the `macros` file. The recursive expansion hickups on `%{name}`, which would only be set from a following specfile, so the expansion aborts and returns the upfront input (`%make_install`).

So, `expandmacros()` should notice that an intermediate `%macro` may not be defined and return the partly-expanded input, just as rpmbuild does. I don't have an idea how to achieve this at the moment.

**Comment by ascherer** [comment]
Problem solved. Recursion gone and replaced by linear loop. `%make_install` and `%{buildroot}` expand just fine; undefined sub-parts are reported as-is. See latest commit.
