### ISSUE TITLE
%_default_verbosity macro doesn't work anymore

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#112]
With the latest release of debbuild, setting `%_default_verbosity 2` in [a macros file](https://build.opensuse.org/package/view_file/Debian:debbuild/debbuild/macros.obs-override?expand=1) doesn't seem to work anymore.

I'm not sure exactly when this broke, but it works with debbuild 18.8.1.

My _guess_ is that something about https://github.com/ascherer/debbuild/commit/384d6b000c6b7c2240cc2d1731c6f6fa7e160ce6 broke this, but I don't know for sure.

**Comment by ascherer** [comment]
If I place `%_default_verbosity N`, with `N=0,1,2` in `~/.debmacros`, the only unexpected (mis-)behavior occurs for `N=2`: in this case you can't get "single verbosity" (`-v`) anymore, only "quiet" (`-q`) and "double verbosity" (`-vv`).

**Comment by Conan-Kudo** [comment]
Hmm, it seems to work fine now. Maybe I accidentally installed debmacros before...
