### ISSUE TITLE
Conditional checks broken with boolean operators ("||", "&&", etc.)

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#13]
I'm not quite sure how, but it seems that conditionals using boolean operators are not working properly.

For example, [my build log of GNU Hello](https://build.opensuse.org/build/home:Pharaoh_Atem/xUbuntu_14.04/x86_64/hello/_log) indicates that it creates `/etc/helloconf/systemd` even on Ubuntu 14.04, when it should be creating `/etc/helloconf/sysv` in that case.

Here's the conditional that is not working correctly:
```
%if 0%{?ubuntu} < 1504 || 0%{?debian} < 8 || 0%{?rhel} < 7 || 0%{?suse_version} < 1230 || 0%{?fedora} < 15
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/sysv
%else
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/systemd
%endif
```

It does work correctly if I chop down the conditional to just the following:
```
%if 0%{?ubuntu} < 1504
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/sysv
%else
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/systemd
%endif
```

See [the full package sources](https://build.opensuse.org/package/show/home:Pharaoh_Atem/hello) if you need more details.

**Comment by ascherer** [comment]
The culprit is in line 662 of 'debbuild': The curious construct with the prepended `0` lead me to the mistaken apprehension that it were possible (or necessary) to deal with 'octal' values. This assumption is only valid as long as there are no digits `8` or `9` in the expression. So, the `eval` in line 666 chokes on `0%{?debian}<8`.

Will investigate ASAP.

**Comment by Conan-Kudo** [comment]
@ascherer [Still broken](https://build.opensuse.org/build/home:Pharaoh_Atem/xUbuntu_15.04/x86_64/hello/_log) (Ubuntu 15.04 writing `sysv` instead of `systemd`)... :(

**Comment by ascherer** [comment]
Guess what: `01504 < 1504` is ... **true**!

I'll investigate this further ...

**Comment by ascherer** [comment]
Could you please try `%{?ubuntu}%{!?ubuntu:0} < 1504`?

**Comment by Conan-Kudo** [comment]
@ascherer That didn't appear to work. I also tried `%{?ubuntu}%{?!ubuntu:0} < 1504`, and that didn't work either.

**Comment by ascherer** [comment]
Thanks for pointing out the bug in the handling of plain-numeric expressions. The recent commit correctly treats all 'numbers' as 'base-10'.

However, the problem with the `%if..%else..%endif` group above is independent of my bug. No matter how `%{ubuntu}` is set, the `%if`-expression will always be **true**:
* Let `%{ubuntu}` be less than `1504`, then the first sub-clause _is_ **true** by nature.
* Let `%{ubuntu}` be `1504` or higher, then the first sub-clause `1504<1504` is **false**, but now the `||` shifts to the second sub-clause `0<8`, which again is **true**.

In order to select 'systemd', _all_ sub-clauses must be **false**, so _all_ 'system' qualifiers must be (a) defined, _and_ (b) greater than the fixed version numbers.

**Comment by ascherer** [comment]
Please don't ask for `%if %{?ubuntu:%{?ubuntu}<1504}%{!?ubuntu:0} || %{?debian:%{?debian}<8}%{!?debian:0} || %{?rhel:%{?rhel}<7}%{!?rhel:0} || %{?suse_version:%{?suse_version}<1230}%{!?suse_version:0} || %{?fedora:%{?fedora}<15}%{!?fedora:0}` to work. I have absolutely no idea how to match all those pairs of curly braces correctly. (rpmbuild _does_ work with this monster.)

**Comment by Conan-Kudo** [comment]
@ascherer So it occurred to me that I might actually be wrong (that is, it's actually doing the *correct* thing by always returning true). After checking some of the RPM builds, I found that you were right, I was evaluating incorrectly. (Which makes it quite interesting how it even worked correctly with the Debian 8 target!!!)

so I flipped the evaluation as such:
```
%if 0%{?ubuntu} >= 1504 || 0%{?debian} >= 8 || 0%{?rhel} >= 7 || 0%{?suse_version} >= 1230 || 0%{?fedora} >= 15
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/systemd
%else
mkdir -p %{buildroot}%{_sysconfdir}/helloconf
touch %{buildroot}%{_sysconfdir}/helloconf/sysv
%endif
```

Now all the RPM based distribution targets work, but Debian and Ubuntu ones don't.

**Comment by Conan-Kudo** [comment]
@ascherer It appears to work correctly with Ubuntu ([14.04](https://build.opensuse.org/build/home:Pharaoh_Atem/xUbuntu_14.04/i586/hello/_log), [15.04](https://build.opensuse.org/build/home:Pharaoh_Atem/xUbuntu_15.04/i586/hello/_log)), but not Debian ([7](https://build.opensuse.org/build/home:Pharaoh_Atem/Debian_7.0/i586/hello/_log), [8](https://build.opensuse.org/build/home:Pharaoh_Atem/Debian_8.0/i586/hello/_log)).

**Comment by ascherer** [comment]
The `>=` is a good alternative. :+1:

I can play with this code
```
%prep
%undefine ubuntu 1504
%define debian 8
%undefine rhel 7
%undefine suse_version 1230
%undefine fedora 15

%if 0%{?ubuntu} >= 1504 || 0%{?debian} >= 8 || 0%{?rhel} >= 7 || 0%{?suse_version} >= 1230 || 0%{?fedora} >= 15
%{echo:systemd}
%else
%{echo:sysv}
%endif
```
and am able to consistently and predictably switch between `systemd` (`%define debian 8`) and `sysv` (`%define debian 7`) for all  settings. (`undefine` is yet another new feature, so please pull the recent version.)

**Comment by Conan-Kudo** [comment]
@ascherer Interesting that it works when you undefine and then define it, but it's not working if you're using it normally (only on Debian though!).

**Comment by ascherer** [comment]
Could it be that 'ubuntu' or an other os is set and causes the `%if` to succeed.

**Comment by Conan-Kudo** [comment]
@ascherer Aha!

`%{debian}` is being assigned the FULL value. For example, on Debian 7.0, it's getting `70` instead of `7`. That's why the evaluation is breaking. It's supposed to have the minor version stripped for Debian, but for some reason, that's not happening (the minor version *does* get chopped off for Ubuntu, though). That's why Debian has `70` or `80` instead of `7` or `8`, while Ubuntu has `1204` or `1404` instead of `12045` or `14043`, etc.

**Comment by ascherer** [comment]
So lines 111-116 of 'debbuild' should be changed accordingly?

**Comment by Conan-Kudo** [comment]
@ascherer Actually, it's just broken on Debian 7.0. Debian 8.0 returns 8 correctly. For some reason, Debian 7.0 does not.

**Comment by Conan-Kudo** [comment]
@ascherer Alright, so it turns out that there was a packaging error when Debian first introduced `/etc/os-release` in Debian 7, and that's why this happened. It was fixed in Debian 7.1, which OBS never sync'd to.

I'm going to poke the OBS folks to fix this by updating to the latest Wheezy point release.

**Comment by ascherer** [comment]
Thanks for looking into this.

**Comment by Conan-Kudo** [comment]
@ascherer Though this is interesting... From Ubuntu builds when using `%{echo:%{debian}}` in %prep.
```
[  166s] <<<%{debian}>>>. Aborting!
```

**Comment by ascherer** [comment]
That's the current reaction, if a `%{macro}` isn't defined. The [recursion in debbuild](https://github.com/ascherer/debbuild/blob/master/debbuild#L1831) dies in [line 1837](https://github.com/ascherer/debbuild/blob/master/debbuild#L1837), if it can't resolve a `%`-element in the input string. Note that this can even happen if, for example, the 'description' section contains a `%`-ted word, so I can't just replace such `%macros` with `<UNDEFINED>` or the like.

**Comment by ascherer** [comment]
To be on the safe side, you can always use `%{echo:%{?debian}}`.

**Comment by Conan-Kudo** [comment]
@ascherer Okay, cool.

**Comment by ascherer** [comment]
[Continuation](https://github.com/ascherer/debbuild/issues/13#issuecomment-162298468):
```
print "\n";

$expr = "%{?ubuntu:%{ubuntu}<1504}%{!?ubuntu:0} || ".
        "%{?debian:%{debian}<8}%{!?debian:0}";
print "input: '$expr'\n\n";

$expr =~ s/%{((?>[^%{}]|(?R))*)}/$1/g;
print "outer removed: '$expr'\n\n";

$expr =~ s/([?!]+)/ $1/g; $expr .= ' ';
print "spaced out: '$expr'\n\n";

while ($expr =~ m/[?!](\w+?):(.+?)\s/g) {
  print "key/value: '$1'->'$2'\n";
}

print "\n";
```

**Comment by ascherer** [comment]
The [recent reimplementation](https://github.com/ascherer/debbuild/commit/679550855c2945f4cdb693cc69f4ce816b89bf8c) of `%{?conditional:macros}` correctly groks the huge [term in my earlier comment](https://github.com/ascherer/debbuild/issues/13#issuecomment-162298468). :white_check_mark:
