### ISSUE TITLE
Conditional make macro usage breaks

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#14]
Using the following expression doesn't seem to work:

```
%{?make_build:%make_build}%{?!make_build:make %{_smp_mflags}}
```

In RPM based distributions, this evaluates correctly, but in debbuild, it breaks with the following output:

```
[  135s] + %{?make_build:/usr/bin/make }
[  135s] /var/tmp/deb-tmp.build.32126: 45: /var/tmp/deb-tmp.build.32126: %{?make_build:/usr/bin/make: not found
[  135s] Can't exec: Inappropriate ioctl for device
[  135s] 
```

Note that using `%make_build` by itself works fine and the following works fine too (this also works on RPM based distributions):

```
%if %{defined make_build}
%make_build
%else
make %{?_smp_mflags}
%endif
```

**Comment by ascherer** [comment]
Yet another case of [nested macros](https://github.com/ascherer/debbuild/issues/13#issuecomment-162298468) that should be expanded in [debbuild](https://github.com/ascherer/debbuild/blob/ee3135273681e694165916d6937e465bc9c191a8/debbuild#L1806).

**Comment by Conan-Kudo** [comment]
@ascherer I suppose I could in this case. It's really only a problem for macros that are parameterized, like for example, `%mkrel` from Mageia.

**Comment by ascherer** [comment]
Idea: use a new associative container for 'parameterized macros'. Use Getopt::Long yet again for argument handling.

**Comment by ascherer** [comment]
Add a few more characters for matching conditional macros: `%`, `{`, `}`, etc.

**Comment by ascherer** [comment]
At least the 'trivial' extension `%{?make_build:%make_build}` doesn't seem to crash anymore. However, [lines 1807](https://github.com/ascherer/debbuild/blob/cd20a15f6a8e61fe8d71d20f5e2d203a1fb9fcbe/debbuild#L1807) and [1822](https://github.com/ascherer/debbuild/blob/cd20a15f6a8e61fe8d71d20f5e2d203a1fb9fcbe/debbuild#L1822) are getting ever more brittle with their hordes of question marks. Time to get the
`(?R)`ecursion going.

**Comment by ascherer** [comment]
Try [Text::Balanced](https://metacpan.org/pod/Text::Balanced).

**Comment by ascherer** [comment]
[Now you're talking, brother!](https://github.com/ascherer/debbuild/commit/5dec91848705cde461edc9687d9599de69a4afef)

**Comment by ascherer** [comment]
Home at last: [release 15.12.1](https://github.com/ascherer/debbuild/releases/tag/debbuild-15.12.1) fixes this (and adds some new features).
