### ISSUE TITLE
Please make new version releases rather than retagging

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#15]
Please just make new releases rather than retagging, because it makes it hard for me to update packages in Fedora and OBS if the version isn't changing.

I noticed you're using the 0.YY.MM format. You could just add a .X to indicate the release and updates. That is, the first version released in a month is 0.YY.MM.0, and successive updates in that month increment the .0 at the end.

**Comment by ascherer** [comment]
D'accord, but I'll start with version `15.12.0` right now.
