### ISSUE TITLE
Adding parameters to %configure breaks with "<switch> not found"

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#16]
I have a spec that I'm using `%configure` with extra parameters attached, but debbuild is not parsing them together.

For example:
```
%configure --enable-doc --disable-static
```

That will run %configure, but then it'll try to run the `--enable-doc and --disable-static` on the next line, and that breaks because it isn't a command. It should be appended to the configure call. I suspect this would affect all the others like it, too.

**Comment by ascherer** [comment]
`chomp` line 388.

**Comment by ascherer** [comment]
Multi-line macros had a `\n` in their `last` line, which separated the 'command' from its (optional) options (`%*` in [rpm's macro parlance](http://www.rpm.org/wiki/PackagerDocs/Macros#DefiningaMacro)).
