### ISSUE TITLE
%check section doesn't work

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#17]
Defining a `%check` section causes the following error when building a package:

```
[   71s] + %{check}
[   71s] /var/tmp/deb-tmp.build.19557: 44: /var/tmp/deb-tmp.build.19557: %{check}: not found
```

Obviously, the `%check` section should work.

**Comment by ascherer** [comment]
Obviously, at least since 2009 (probably much longer).

**Comment by ascherer** [comment]
At the time of writing, `make test` should be added to the `%install` section.

**Comment by ascherer** [comment]
Note to self: DRY.

**Comment by ascherer** [comment]
[Commit 222](https://github.com/ascherer/debbuild/commit/beacb2cd68886c7011f3bdad597f617555e1e750) fixes this nice and clean.
