### ISSUE TITLE
[RFC/RFE] PreReq / Pre-Depends

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#19]
I've been going back and forth on this a bit. While in RPM, `PreReq` doesn't really do anything special anymore (It's essentially mapped to `Requires(pre)` and `Requires(preun)` now, which means that the package must be installed before the pre-(un)install scriptlet can be run, if any exist in the package spec), in Debian, it seems that `Pre-Depends` are still important in some cases. [According to the Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-relationships.html), `Pre-Depends` essentially enforce that a required package must be fully installed before the package requiring it can even be unpacked.

Now, that said, Debian Policy *strongly* discourages the use of `Pre-Depends`, and all RPM based distributions do the same with `PreReq`. However, there is no equivalent to RPM's scriptlet level Requires (and there are cases where we do actually need the `Pre-Depends` capability), so in order to have the same effect, something has to be done here to ensure that we can get that.

There are two approaches here:

* Mapping `Requires(pre)` and `Requires(preun)` to `Pre-Depends`. This is not semantically identical (though it is close), but since the equivalent behavior no longer exists in RPM because package managers like Yum and DNF essentially enforce that dependent packages are "installed" before installing the main package, this would work well enough in terms of ensuring the _intended_ behavior is represented between the two systems in a common spec.

* Enabling `PreReq` and mapping it to `Pre-Depends`. This is semantically identical, but the former is *really* not supported in modern versions of RPM in the way `Pre-Depends` works, so it might give a false impression of what it does. It also makes `rpmbuild` unhappy and throw out deprecation warnings.

I'm personally leaning towards actually enabling both approaches. If someone does define `Requires(pre)` and `Requires(preun)`, these would be collected and turned into `Pre-Depends`. Likewise, anything defined with `PreReq` would be added to the `Pre-Depends` list. If we don't already parse `Requires(post)` and `Requires(postun)`, those should be added to the `Depends` list.

What do you think?

**Comment by ascherer** [comment]
I have pushed [a new commit](https://github.com/ascherer/debbuild/commit/d613856f34092ae4dc3a396c33a40b51578b9456), which supports this:
```
%if %{_vendor} == "debbuild"
Pre-Depends: [list of pre-installation dependencies]
%else
Requires(pre): [list of pre-installation dependencies]
%endif
```
Scanning and storing `Requires(pre)` correctly seems quite involved; I wouldn't want to do this at this time. (That's also the reason why I haven't found a decent solution for your Issue #1 yet.)

**Comment by Conan-Kudo** [comment]
@ascherer You could just map `PreReq` to `Pre-Depends` as a simple solution for now. That will eliminate the need for a vendor conditional.

**Comment by ascherer** [comment]
I'd [rather not](https://github.com/ascherer/debbuild/blob/d613856f34092ae4dc3a396c33a40b51578b9456/debbuild#L758), due to RPM's deprecation warning.

**Comment by Conan-Kudo** [comment]
@ascherer You could similarly throw a warning about it. As it is, it's a big annoying misfeature that exists only because apt for dpkg doesn't guarantee that all dependencies are installed prior to unpacking the package intended to be installed unless you tell it to with `Pre-Depends`. Heck, I think smart handles this correctly like Yum/DNF for Debian.

**Comment by Conan-Kudo** [comment]
@ascherer With how you've managed to improve things on how dependency processing has improved, do you think you could get `Requires(pre)` and `Requires(preun)` to map to `Pre-Depends` in debbuild now?

**Comment by ascherer** [comment]
I'll have a look.

**Comment by ascherer** [comment]
Done for release 16.1.8.
