### ISSUE TITLE
macro names aren't preserving case sensitivity

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#22]
Apparently, two different macros that have the same name but different cases aren't being treated as different. This behavior differs from `rpmbuild`.

for example:
```
%define _Main_path /opt/Program
%define _main_path /opt/program
```
The above definitions are treated the same, so `%{_Main_path}` gets redefined to be `/opt/program`.

**Comment by Conan-Kudo** [comment]
So I tried actually only defining `_Main_path`, and debbuild completely ignores the definition. So it seems that it doesn't like case sensitive definitions at all.

**Comment by ascherer** [comment]
Thanks for the bug report. I wasn't aware that `%_CamelCase_Macros` were possible, when I broke this behavior in commit 68be72a11f392953d3a314a72e1baa36b4a38515.
