### ISSUE TITLE
[RFE] %autosetup and %autopatch (or... lua powered macros)

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#23]
As of RPM 4.11.x, there are the `%autosetup` and `%autopatch` macros ([see them here in RPM git master](https://github.com/rpm-software-management/rpm/blob/master/macros.in#L1062)). These macros are special as they are implemented with a mix of traditional macros and Lua scripting.

I don't know if it's possible to implement [the Lua interface](http://www.rpm.org/wiki/PackagerDocs/RpmLua), though if it is possible, that would be preferred. 

However, it would be nice if we could have` %autosetup` and `%autopatch` in debbuild, as it does make some annoying stuff go away (like doing `%patchN` macros for each Patch, or crazy numbers of `%setup` invocations with multiple Sources).

**Comment by ascherer** [comment]
`%autopatch` should be fairly easy to implement: around line 753/754, process "all available patches" (see `srcpackage()`) into a genuine `%patch` line of the form `%patch -P 0 1 2 3 ... [-p1]` and fall through to `process_patch()`.

`%autosetup` could follow as a shortcut to `%setup` plus `%autopatch`.

Adding support for `-S git` might get involved.

**Comment by Conan-Kudo** [comment]
@ascherer They don't necessarily need to be in macros.in, I suppose. It'd be useful for some level of flexibility, but probably not required. As for supporting the SCMs, supporting the various types of patch application methods would be quite useful.

**Comment by ascherer** [comment]
An elementary version of the `%autopatch` command is in place.

**Comment by ascherer** [comment]
And an elementary version of the `%autosetup` command follows right away. See [mmix.spec](https://github.com/ascherer/mmix/blob/local/mmix.spec) for a first application.

**Comment by ascherer** [comment]
You may also want to make use of [this EXPERIMENTAL feature](https://github.com/ascherer/debbuild/commit/9c937fa9dd219acc8c1b6192a0985457824a0015).

**Comment by ascherer** [comment]
Hooray! It works, `-S git` inclusive.
