### ISSUE TITLE
Parameterized macros do not work in debbuild

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#24]
So I've been working on implementing parameterized macros for using in specs with debbuild, and I've stumbled on being able to use a couple. It doesn't seem to evaluate them at all, unlike on RPM, where it worked (tested on RPM 4.13 on Fedora 23 and debbuild 16.1.8 on Ubuntu 15.10).

Here's a few parameterized macros that I've attempted to use, with no success on debbuild (they work on RPM, though):

Macro for generating the symbols file for libraries:
```
%__dpkg_gensymbols /usr/bin/dpkg-gensymbols

# Macro: %{mklibsymbols <name> <major>}
# Generates the symbols file for a Debian package
%mklibsymbols() \
mkdir -p %{buildroot}/%{1}/DEBIAN \
%{__dpkg_gensymbols} -P%{buildroot} -p%{1} -v%{version}-%{release} -e%{buildroot}%{_libdir}/%{1}.so.%{2} -e%{buildroot}%{_libdir}/%{1}.so.%{2}.* -O%{buildroot}/%{1}%{2}/DEBIAN/symbols \
%{nil}
```

Macro for generating library package names (adapted from Mageia):
```
# Macro: %{mklibname <name> [<major> [<minor>]] [-s] [-d]}
# - %{mklibname test}           => libtest
# - %{mklibname test 1 -d}      => libtest1-dev
# - %{mklibname test 1 -d 0 -s} => libtest1_0-static-dev
%mklibname(ds)  lib%{1}%{?2:%{2}}%{?3:_%{3}}%{-s:-static}%{-d:-dev}
```

Macro for pre-uninstall action with systemd services (adapted from systemd upstream):
```
%systemd_preun() \
if [ $1 == "remove" || $1 == "purge" ]; then \
        # Package removal, not upgrade \
        systemctl --no-reload disable %{?*} > /dev/null 2>&1 || : \
        systemctl stop %{?*} > /dev/null 2>&1 || : \
fi \
%{nil}
```

**Comment by Conan-Kudo** [comment]
Here are some example invocations:

* `%mklibsymbols test 0` (alternatively `%{mklibsymbols test 0}`)
* `%mklibname test -d` (alternatively `%{mklibname test -d}`)
* `%systemd_preun test.service` (alternatively `%{systemd_preun test.service}`)

**Comment by ascherer** [comment]
[Start here](https://github.com/ascherer/debbuild/blob/master/debbuild#L1692).

**Comment by ascherer** [comment]
May I request/impose that options and arguments are sorted, i.e.,
```
%{mklibname test 1 -d 0 -s}
```
should rather be
```
%{mklibname -d -s test 1 0}
```
for the sake of Getopt::Std.

**Comment by Conan-Kudo** [comment]
@ascherer They are already ordered, but if it's really quite difficult to support arbitrary orderings, I can reorganize them. Just tell me what the rules are, and hopefully the behavior should still work as expected when run on rpm. (I want to preserve macro compatibility if at all possible).

**Comment by ascherer** [comment]
`Getopt::Std::getopts()` stops at the first non-option, i.e., the first version doesn't separate options and arguments at all, because it stops at `test`. The second version correctly spots the two options and leaves the three arguments in `@ARGV` (in order). I _could_ try to move options up-front, but then you'll come up with parametrized options. :wink: 

See https://github.com/ascherer/debbuild/tree/macros-with-options-and-arguments for a very rudimentary experiment, where I try to call `handle_macro_options()` in `expandmacros()`.

**Comment by Conan-Kudo** [comment]
I see. I'm surprised that Perl doesn't have better/more flexible option parsers, given what Perl has historically been used for... :/

**Comment by ascherer** [comment]
If I interpret [man getopt(3)](http://linux.die.net/man/3/getopt) correctly, `Getopt::Std::getopts()` is POSIX correct, when it does _not_ put non-options to the end.

**Comment by ascherer** [comment]
Commit https://github.com/ascherer/debbuild/commit/f79e4c88def0b27f85f8148283be4bc04dac3009 makes `handle_macro_options()` deal with macros that have options (with parameters) and non-option arguments, possibly mixed.

**Comment by ascherer** [comment]
Could you please try commit https://github.com/ascherer/debbuild/commit/2da9d60a270b62174b1b84532d45f4c6032a2d25 and report that it works as expected?

**Comment by ascherer** [comment]
I found [one reference](http://ftp.novell.hu/pub/mirrors/ftp.novell.com/forge/library/SUSE%20Package%20Conventions/spc_rpm_macros.html) that claims that "all options must be defined before parameters". However, if you claim that **rpm** _does_ handle your macros as desired, **debbuild** certainly should do the same.

Moreover, **debbuild** provides
* `%{?2}` as a short-cut for `%{?2:%{2}}`
* `%{!?3:_42}` for when the third non-option argument is _not_ provided
* `%N` is short-cut for `%{N}`, `N` numeric

**rpmbuild 4.9.1.1** groks all these special cases. I wonder if there is a full documentation of this feature.

**Comment by Conan-Kudo** [comment]
Here's [the original `%mklibname` from Mageia](http://gitweb.mageia.org/software/rpm/rpm-setup/tree/build.macros.in#n171). I'm fairly certain they would be upset if it didn't work, since it's a macro that they use everywhere, per their policy. Here's [my variant for Fedora](http://copr-dist-git.fedorainfracloud.org/cgit/ngompa/mga-compat-macros/mga-srpm-compat-macros.git/tree/macros.mga-mklibname). The version I gave you as an example isn't far off from it.

I talked to Florian Festi in `#rpm.org` on Freenode, and he noted it's one of the few things that hasn't been rewritten, and "full" documentation doesn't seem to exist on the topic. There's [this page on the RPM wiki](http://www.rpm.org/wiki/PackagerDocs/Macros), but not much else.

I'll try out the commits in question and report back soon.

**Comment by ascherer** [comment]
Commit https://github.com/ascherer/debbuild/commit/9761f2ccf963ac66001ab47bbb7563ed63ded228 is the release candidate for **debbuild 16.2.0**.

**Comment by Conan-Kudo** [comment]
It doesn't seem to be working correctly.

```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%systemd_preun test.service"
if [ $1 == "remove" || $1 == "purge" ]; then \
        # Package removal, not upgrade \
        systemctl --no-reload disable %{?*} > /dev/null 2>&1 || : \
        systemctl stop %{?*} > /dev/null 2>&1 || : \
fi \
 test.service
```

```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%mklibname test -d"
lib%{1}%{?2:%{2}}%{?3:_%{3}}%{-s:-static}%{-d:-dev} test -d
```

```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%mklibsymbols test 0"
mkdir -p /home/ngompa/debbuild/BUILDROOT/%{name}-%{version}-%{release}.amd64/%{1}/DEBIAN \
/usr/bin/dpkg-gensymbols -P/home/ngompa/debbuild/BUILDROOT/%{name}-%{version}-%{release}.amd64 -p%{1} -v%{version}-%{release} -e/home/ngompa/debbuild/BUILDROOT/%{name}-%{version}-%{release}.amd64/usr/lib/%{1}.so.%{2} -e/home/ngompa/debbuild/BUILDROOT/%{name}-%{version}-%{release}.amd64/usr/lib/%{1}.so.%{2}.* -O/home/ngompa/debbuild/BUILDROOT/%{name}-%{version}-%{release}.amd64/%{1}%{2}/DEBIAN/symbols \
 test 0
```

**Comment by ascherer** [comment]
Please wrap the input to `--eval` in "curly braces", like
```
%{system da preun test.service foo.service bar.service}
%{my lib name test -d 0 -s}
%{my lib symbols test 0}
```

**Comment by Conan-Kudo** [comment]
So this looks good, but should I be concerned about the slashes around quote marks? If those are showing up, does that mean they'll show up in the scriptlets (which would break them entirely...)?
```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%{systemd_preun test.service foo.service bar.service}"
if [ $1 == \"remove\" || $1 == \"purge\" ]; then
        # Package removal, not upgrade
        systemctl --no-reload disable test.service foo.service bar.service > /dev/null 2>&1 || :
        systemctl stop test.service foo.service bar.service > /dev/null 2>&1 || :
fi

```

```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%{mklibname test 0 -d -s}"
libtest0-static-dev

```

```
ngompa@u1510-dev-f23kvm:~/Downloads$ debbuild --eval "%{mklibname test 0 2 -d -s}"
libtest0_2-static-dev

```

Also, each of these seem to print out an extra newline... Should I be concerned about that when using it in a spec, because some of these are going to be used in things where new lines are clearly unexpected behavior...

**Comment by ascherer** [comment]
The catching problem comes from [here](https://github.com/ascherer/debbuild/blob/master/debbuild#L1668). The quoting and newline problems will also be fixed ASAP.

**Comment by ascherer** [comment]
RC2: https://github.com/ascherer/debbuild/commit/18ec01e082ffa911cfaff860d61e78f9ced7d353
All _my_ test projects compile fine. Please test the new macros inside specfiles.

**Comment by ascherer** [comment]
RC3: https://github.com/ascherer/debbuild/commit/85f2a8079dcf14ab49abad9a21eac1d54dc54f8d

**Comment by Conan-Kudo** [comment]
With RC2, I was able to use the macros only if I encapsulated them in with curly braces. Using them the way I had in Mageia/Fedora did not work correctly. Also, I think I discovered another (unrelated) problem that I'll be filing a bug about soon, once I dig more into it.

**Comment by ascherer** [comment]
If you mean something like [this](https://wiki.mageia.org/en/Libraries_policy), then I think I'll pass.

**debbuild**'s macro "interpreter" is distributed over `parse_spec()`, `expandmacros()`, and recently `handle_macro_options()`, and simply _does not_ parse all constructs the same way as **rpmbuild**. Especially, it does _not_ "look ahead" in general situations.

While `parse_spec()` can automatically wrap non-bracketed input **lines** _as a whole_ in curlies for the sake of `expandmacros()` and `handle_macro_options()`, it does this _not_ inside input lines like the `%define` lines of the Mageia example. In such cases, the specfile author is required to add the correct curly braces around the macros and their options and arguments.

**Comment by Conan-Kudo** [comment]
@ascherer That's fine. As long as I know of the limitation, I can deal with it.

I'll need to double check to be sure it wasn't an issue when I was using it standalone, though.

**Comment by ascherer** [comment]
On the other hand, the special case `%define` _could_ be addressed in [line 1661](https://github.com/ascherer/debbuild/blob/85f2a8079dcf14ab49abad9a21eac1d54dc54f8d/debbuild#L1661). Here, `value` could be checked if it starts with a "parametrized macro", and if it does, wrapped in curly braces for the call of `expandmacros()`.

Are there more examples and situations how `%mklibname` etc. are applied?

**Comment by Conan-Kudo** [comment]
It's often used to generate the correctly named (Build)Requires for a library (especially if they're named differently for 64-bit and 32-bit), so something like this is possible:

```
BuildRequires: %mklibname pcap -d
Requires: %{mklibname pcap 1} > 1.4.0
```

And as I've mentioned mentioned before, it's used typically to define the properly structured names for packages, which are often used all over the spec (either as Provides, Requires, BuildRequires, package names, etc.):

```
# Original library name is libfoo
%global shortname foo
%global libname %mklibname %{shortname} 1 2
%global devname %mklibname -d %{shortname}
```

**Comment by ascherer** [comment]
I'll take a look.

**Comment by ascherer** [comment]
Question: Has the leading space in in the replacement for option `%{-c}`
```
%mkrel(c:) %{-c: 0.%{-c*}.}%{1}%{?subrel:.%subrel}%{?dist:%dist}
```
a special purpose?

**Comment by Conan-Kudo** [comment]
@ascherer I'm not exactly sure. My `%mkrel` is derived from [the version from Mageia](http://gitweb.mageia.org/software/rpm/rpm-setup/tree/build.macros.in#n143), and that one has the leading space...

If I had to guess, I don't think so, but I'm not completely sure...

**Comment by ascherer** [comment]
I've added commit 2807fc9 that permits whitespace after the colon.

**Comment by ascherer** [comment]
It seems that commit 4206011 fixes all details of this request, so I declare it as RC4 and final.

**Comment by ascherer** [comment]
I'm shipping the new release 16.2.0 despite the related open issue #29.
