### ISSUE TITLE
Conditional definition not working in spec

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#26]
I tried using the following in a spec today, and it didn't seem to work:

```
%{?!_unitdir:%global _unitdir /lib/systemd/system}
%{?!_initddir:%global _initddir /etc/init.d}
%{?!_jobsdir:%global _jobsdir /etc/init}
```

They remained undefined anyway, even though it is supposed to define them in the event they are not defined.

**Comment by ascherer** [comment]
Start around line 1748; I'm not sure if this ever worked in **debbuild**.

**Comment by Conan-Kudo** [comment]
@ascherer I thought this did work at one point after you got #4 in place?

**Comment by ascherer** [comment]
I'll check this tomorrow.  Maybe the 'equivalence' logic needs some grouping to keep `$value` intact. At first glance it _looks_ OK.

**Comment by ascherer** [comment]
I'm quite sure that this has never worked in **debbuild**. The 'preamble' processing silently skipped such lines in `parse_spec()`. Moreover, if such input is processed by `expandmacros()`, the `%global` part is executed unconditionally, way before the 'conditional macro' loop is run. At that time there's not much left of the right side and the macros themselves contain the right curly brace.
