### ISSUE TITLE
Bug in macro option handling

### ISSUE THREAD

**Issue by ascherer** [ascherer/debbuild#29]
`%__scm_apply_svn` isn't correctly processed because of the space in `%{-p:--strip %{-p*}}`.

**Comment by ascherer** [comment]
85f2a8079dcf14ab49abad9a21eac1d54dc54f8d is the first bad commit

**Comment by ascherer** [comment]
There's some potentiality for improvement.

**Comment by ascherer** [comment]
The problem is that `%apply_patch` contains `%{expand:%{__scm_apply_patch ...}}`, so the "option handling loop" has to act on the associated options "two levels down".
* The `%{\w}` options belong to `%apply_patch`
* have to be extracted for `%__scm_setup_patch`
* and must then replace the `%{\w}` options in _that_ definition

This _prohibits_ anything but `\S` in the search pattern.

**Comment by ascherer** [comment]
All this effort won't lead to much. As I've just found, the whole expansion hotch-potch breaks down, because the `%{-m*}` parameter of `%apply_patch(qp:m:)` is filled with an extra complicated
`%{basename:/path/o/patch/file}`, which hickups at any level of `bracelet()`-loop.

With a _lot_ of time, it _could_ be worthwhile to look at [Parse-RecDescent](https://github.com/jtbraun/Parse-RecDescent) and write a genuine macro parser.

**Comment by ascherer** [comment]
The bug is less related to SVN, but more to `%apply_patch` itself. This "high level" macro is causing even more trouble.

**Comment by ascherer** [comment]
It's easier to fix issue #30 than the whole conundrum of `bracelet()` loops necessary for "general macro option handling". So `%apply_patch(qp:m:)` wins over SVN support.

**Comment by Conan-Kudo** [comment]
@ascherer This didn't break the other SCMs, right?

**Comment by ascherer** [comment]
No worries,  `-S git` works just fine. However, it is _not_ possible to define "multi-level" macros with options,  because of the many interdependencies between the stacked `bracelet()` loops. I don't have the time to analyse this more thoroughly.
