### ISSUE TITLE
"%global somajor 0" does not define "%{somajor}" as "0"

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#31]
I just discovered that setting `%global somajor 0` does not work as expected. Instead of actually defining it literally as zero, it leaves it undefined.

This is inconsistent with `rpmbuild` behavior, and is necessary if you're trying to do file lists and restricting based on shared object major versions.

**Comment by ascherer** [comment]
Thanks for catching this. To bad that numerical '0' also acts as truth value 'false'.
Also ``debbuild --define="somajor 0" --eval="%somajor"`` was broken.
