### ISSUE TITLE
ldd is run even when the package/subpackage is set as 'noarch'

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#33]
Obviously, noarch packages shouldn't have binary data and binary dependency detection, but it seems that it runs anyway. There are unfortunately circumstances where noarch packages may have files with the executable permissions bit (Python scripts, etc.), but if a package or subpackage is declared as noarch, it should not run ldd on the files in that package/subpackage. ldd just blows chunks when it runs on those files.

**Comment by ascherer** [comment]
Check `$pkgdata{main}{arch}` on entry to `getreqs()`.
