### ISSUE TITLE
debbuild %{version} and %{release} variables chopping off values with '+' or '~' when used in a spec

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#38]
It is completely valid for the version and release fields to include `+` and `~` in it. However, when they are used in the Version or Release fields, the corresponding variable insertion doesn't work as expected. It cuts off at the `+` and the rest of it isn't inserted, leaving things like the following not work properly:

```
Version: 0.9.9+20160304.1346
Release: 1%{?dist}

%global libname libmoo0

[...]
Requires: %{libname}%{?_isa} = %{version}-%{release}
```

The above renders in the built deb as `Depends: libmoo0 (= 0.9.9)`, which is invalid and doesn't resolve.

**Comment by ascherer** [comment]
Check 'splitver()'.

**Comment by Conan-Kudo** [comment]
Incidentally, these are now valid characters for RPM as well. RHEL/CentOS 6 received a backport to support it, and it's been supported in all distributions using RPM 4.10 or newer.
