### ISSUE TITLE
[RFE] Support complex macro logic and %bcond logic

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#4]
In `rpmbuild`, it is possible to adjust the conditions and build for a spec using `--with <flag>` and `--without <flag>`. In RPM, these are automatically converted to the appropriate internal flag definitions.

In RPM spec files, these can be utilized in a couple of ways:

* Using `%if %{defined _with_flag}`, `%if %{undefined _with_flag}`, `%if %{defined _without_flag}`, and `%if %{undefined _without_flag}`.

   * With this type of check, I don't care what the value is, only that it exists. However, note that the value set by `rpm`/`rpmbuild` is not an integer, so things like `%if 0%{?_without_flag}` makes it bomb out.

   * An example:
   ```
   %if %{defined _without_stuff}
   ... do things ...
   %endif

   %if %{undefined _with_stuff}
   ... do things ...
   %endif
   ```

* Using `%{?_without_flag:<output>}`, `%{?!_without_flag:<output>}`, `%{?_with_flag:<output>}`, and `%{?!_with_flag:<output>}`

   * With this type of check, I can have it write out a line only in the event of the appropriate flag being passed at the build command. `?` checks for if it is defined, while `?!`/`!?` checks if it is undefined.

   * An example: `%{?_without_stuff:BuildRequires: git}`

Additionally, I can pre-set defaults in the spec that will be honored at build by declaring what the options are using `%bcond_with <flag>` and `%bcond_without <flag>`.

* `%bcond_with <flag>` indicates that the **default** is defined as the equivalent of `--without <flag>`. Thus, in order to enable it, you must pass in `--with <flag>` on the build command. Meaning, it's saying that the flag is ***disabled by default***, and can be enabled by passing in the switch noted earlier.

* `%bcond_without <flag>` indicates that the **default** is defined as the equivalent of `--with <flag>`. Thus, in order to disable it, you must pass in `--without <flag>` on the build command. Meaning, it's saying that the flag is ***enabled by default***, and can be enabled by passing in the switch noted earlier.

Having this functionality in `debbuild` will allow for more advanced and useful complex build control logic by build systems and the like.

**Comment by ascherer** [comment]
Looks challenging.

**Comment by ascherer** [comment]
With the newly improved option handling,  it should be straightforward to implement `--with` and `--without`. Let's see where this leads to.

**Comment by ascherer** [comment]
The first two bullet points are in place.
* `--with <flag>` defines macro `_with_<flag>` as `--with-<flag>`
* `--without <flag>' defines macro `_without_<flag>` as `--without-<flag>`
* `%{defined <flag>}` returns `1` if `<flag>` is defined, `0` otherwise
* `%{undefined <flag>}` returns `0` if `<flag>` is not defined, `1` otherwise
* `%{?<flag>:<replacement>}` is extended for caps and whitespace
* dito for `%{?!<flag>:<replacement>}`

**Comment by ascherer** [comment]
will merge 'bcond' branch and close this issue next week.

**Comment by ascherer** [comment]
I already _do_ have a nice application for this stuff! My Linux Mint installation doesn't have TeX, so I have to exclude the creation of target 'fullmanual':
```
%bcond_with fullmanual
...
%if %{without fullmanual}
sed -e "..." -i Makefile
%endif
```
and invoking `debbuild --without fullmanual ...`. :cool:

**Comment by Conan-Kudo** [comment]
@ascherer Nice things are nice, aren't they. :+1:

**Comment by ascherer** [comment]
debbuild 0.15.11a has all this and more. Enjoy!
