### ISSUE TITLE
Explicit "Requires" are being written as "Pre-Depends"

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#40]
When specifying "Requires", they are being processed into "Pre-Depends" instead of "Depends" for some reason.

**Comment by ascherer** [comment]
I can't confirm this. `debbuild.spec` has at least one explicit 'Requires:' and this comes out as 'Depends:' in the package `control` file.

**Comment by Conan-Kudo** [comment]
@ascherer I've only seen it happen when packages have autogenerated `Depends` too.

**Comment by ascherer** [comment]
OK, there seems to some problem with mixed reqirements. In one non-'noarch' package, an explicit 'Requires:' was swallowed and only two implicit packages are listed in `control`.

**Comment by ascherer** [comment]
False positive: I tested with 'BuildArch: i386' on 'amd64', so the package analyzer requested changes for 'libc6' et al. (_and_ I had additional text after the package list that fowled up the result even more). After adapting the correct setting, explicit 'Requires:' in the .spec file and auto-generated package dependencies were merged correctly. Could you please provide a (non-) working example that shows the defect?
