### ISSUE TITLE
Distribution detection is now completely broken

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#45]
As of c175a65f2ee15f2a8526888c723d6cb2d9d8f553, the existence of `lsb_release`  is now a hard dependency. This should not be the case, as the `lsb_release` program and `/etc/lsb-release` are deprecated for [os-release(5)](https://www.freedesktop.org/software/systemd/man/os-release.html), which exists as `/etc/os-release`.

All the original logic that supported `/etc/os-release` was unnecessarily purged. Debian doesn't even provide the legacy LSB files in a default install (only Ubuntu did). Most other distributions never supported it either. The old logic supported os-release(5) and lsb-release data, using `/etc/os-release` if it existed, and falling back to lsb-release data if it didn't.

os-release(5) is supported on Debian 7 and up, Ubuntu 12.04 and up, and all derivatives, out of the box. It's also supported on RHEL/CentOS 7 and up, Fedora, openSUSE, SUSE Linux Enterprise 11 SP4 and up, Mageia, and others.

Older distributions that needed detection merely needed to have `/etc/lsb-release` available in some fashion.

**Comment by ascherer** [comment]
Excellent! That's exactly the reaction I wanted to get with my provocation. I'm not familiar with either convention, so I picked one from [this thread](http://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script) and it happened to be `lsb_release` that popped up repeatedly.
