### ISSUE TITLE
debbuild creates debs for which there are no %files sections

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#47]
debbuild seems to be generating debs for packages/subpackages that have no `%files` list. Per RPM behavior, it should not generate a package for anything (even the primary package name) if there's no `%files` counterpart for this.

For example, if a spec has name `foo`, but only has a `%files` list for a subpackage `bar`, it should only generate a deb for `bar`, and ignore `foo`. debbuild currently makes an empty `foo` too.

**Comment by ascherer** [comment]
This _should_ be caught in line 1208. Will investigate.

**Comment by ascherer** [comment]
A "main" package without a "%files" section does not produce a "binary" `.deb` file.

**Comment by Conan-Kudo** [comment]
@ascherer 

What about when a subpackage has files, but the main package does not?

**Comment by ascherer** [comment]
I'll have to set up a test specfile for this situation.

**Comment by ascherer** [comment]
I don't know what you are doing, but I can't reproduce the described problem. Adding `%package sub` to a simple specfile (with its own `Summary:` and `%description`; other than rpm, debbuild automatically transfers the main `Group:` to each subpackage without an individual group setting) and extending all build- and output-related steps with `sub` (including the ominous `%files` section) results only in the sub-`.deb` (and the main `.sdeb`).

**Comment by Conan-Kudo** [comment]
@ascherer I think I know now... If there are `Requires` specified in the main package, it will make it, because it doesn't know to ignore everything about the main package if the file list section doesn't exist.

**Comment by ascherer** [comment]
Don't take `Requires:` into account when checking "non-empty" packages.

**Comment by Conan-Kudo** [comment]
@ascherer Will it still generate the main package if you have a `%files` section that's empty? Because that behavior is permitted in RPM, too.

**Comment by ascherer** [comment]
I've added an empty `%files` section (in addition to the non-emty `%files sub` section) in my test specfile, and `debbuild -ba foo` _only_ creates `foo-sub.deb` and `foo.sdeb`.

**Comment by Conan-Kudo** [comment]
@ascherer Is there a way to make so that it would create a package (or subpackage) when an empty `%files` section exists? Creating metapackages should be possible...

**Comment by ascherer** [comment]
Well, according to the former comment around "line 1208", Kris tried this with his implementation by reacting to a non-empty `Requires:` list. This could be seen as quite logical, because a "meta-package" might be the appropriate object to place external dependencies. I have no idea how rpm works in all these border-cases. :crystal_ball:

**Comment by Conan-Kudo** [comment]
Is there a concept of `NULL != ""` in Perl? Because then you could say "if `%files` is not defined for this package, then don't do it, otherwise process everything". If not, restore the original behavior and document it.

The reason RPM is able to work the way it does is that it processes file lists first. The file list triggers processing the metadata associated with it and running dependency generators for each package built from the spec. If there's no file list section associated with a package name, it'll completely skip it. It literally has no idea about packages until it figures out the file lists.

This is also why RPM is able to provide you lists of files installed but unpackaged. As of now, `debbuild` doesn't provide this capability, but I'm not sure that's even possible.

**Comment by ascherer** [comment]
At least [Fedora suggests non-empty `Requires:`](https://docs.fedoraproject.org/en-US/Fedora_Contributor_Documentation/1/html/Software_Collections_Guide/sect-Creating_a_Meta_Package.html) when building meta-packages.

**Comment by Conan-Kudo** [comment]
@ascherer Yes, it does, and note the `%files` with no entries in there.

**Comment by ascherer** [comment]
I've rolled back to `debbuild-16.9.3` and Kris' idea. :relaxed:

**Comment by Conan-Kudo** [comment]
Okay.
