### ISSUE TITLE
"<" and ">" need to be translated to "<<" and ">>"

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#49]
While working on a package and building it, I noticed the following message:

```
[  133s]  'Conflicts' field, reference to 'libpkg':
[  133s]  '<' is obsolete, use '<=' or '<<' instead
[  133s] dpkg-deb: warning: ignoring 1 warnings about the control file(s)
```

According to the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-relationships.html), `<` and `>` should not be used. `<` means "less than or equal to" rather than "strictly less than". Basically, when `<` and `>` are being read in the spec file, they need to be replaced with `<<` and `>>` in order to correctly map the relationship.

**Comment by ascherer** [comment]
Modify the end of `splitver()` (around line 1400) as follows
```
  my ($pkg,$rel,$ver) = $req =~ /([\w.+-]+)\s*([><=]+)\s*([\w:.~+-]+)/;
  $rel = '<<' if $rel eq '<';
  $rel = '>>' if $rel eq '>';
  return ($pkg,$rel,$ver);
```

**Comment by ascherer** [comment]
Even cooler is
```
$rel =~ s/^([><])$/\1\1/;
```
