### ISSUE TITLE
Add support for %{expand: ... } in macros

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#52]
Some RPM macros may require expansion/evaluation multiple times to fully flesh out. For macros like these, RPM has the `%{expand: ... }` macro to support this.

Per [the documentation](http://rpm.org/user_doc/macros.html):
```
	%{expand:...}	like eval, expand ... to <body> and (re-)expand <body>
```

This would be useful for contexts like properly supporting Debian multiarch in macros, rather than applying stuff at install time through a scriptlet, or supporting [the new Python macros](http://pkgs.fedoraproject.org/cgit/rpms/python-rpm-macros.git/tree/).

**Comment by ascherer** [comment]
`debbuild`'s `%[expand:...}` as used for CBS and SCM is quite limited for general use.

**Comment by Conan-Kudo** [comment]
I tried evaluating `%py3_build` after installing `macros.python3`, and this is what I got from debbuild:

```
ngompa@ubuntu-f25kvm:/usr/lib/debbuild/macros.d$ debbuild --eval %py3_build
%{expand:
  CFLAGS="%{optflags}" /usr/bin/python3 %{py_setup}  build --executable="/usr/bin/python3 -s" %{?*}
```

This is what my Fedora system does:

```
[ngompa@f25kvm ~]$ rpm -E "%py3_build"

CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic" /usr/bin/python3 setup.py  build --executable="/usr/bin/python3 -s" ;
sleep 1

```

There's definitely significant difference in macro expansion capabilities.

**Comment by ascherer** [comment]
Multi-line arguments to `%{expand:...}` are not supported at this time.
