### ISSUE TITLE
Macros that exec commands not working inside conditional

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#55]
When trying to wrap something in a conditional, macros that exec commands don't seem to work.

For example, the following does not work:
```
%{!?__python3:%global __python3 /usr/bin/python3}
%{!?python3_sitelib:%global python3_sitelib %(%{__python3} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")}
```

However, this does work:
```
%global __python3 /usr/bin/python3
%global python3_sitelib %(%{__python3} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")
```

But I only want it to be defined if a definition doesn't already exist.

**Comment by ascherer** [comment]
The longer version works:
```
%if %{undefined python3_sitelib}
%global python3_sitelib %(%{__python3} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")
%endif
```

**Comment by ascherer** [comment]
The [jump to `CONDMAC:`](https://github.com/ascherer/debbuild/blob/master/debbuild#L1625) skips over much of the processing logic. Recursive calls to `expandmacros()` may well have an escaped argument and don't trigger the correct handler loop(s).

**Comment by ascherer** [comment]
Test case broken.

**Comment by ascherer** [comment]
I _knew_ I was close.
