### ISSUE TITLE
%autosetup/%autopatch doesn't work

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#56]
I get the following error when I use `%autosetup -p1` or `%autopatch -p1`:

```
[   76s] + cd /home/abuild/debbuild/BUILD
[   76s] + /bin/rm -rf libubox-0~git20161205.1480957910.f9db1cb
[   76s] + /usr/bin/xz -dc /home/abuild/debbuild/SOURCES/libubox-0~git20161205.1480957910.f9db1cb.tar.xz
[   76s] + /bin/tar -xf -
[   76s] + STATUS=0
[   76s] + [ 0 -ne 0 ]
[   76s] + cd libubox-0~git20161205.1480957910.f9db1cb
[   76s] + /bin/chmod -Rf a+rX,u+w,go-w .
[   76s] + test -f 0001-Fix-CMakeLists-to-detect-dependencies-and-install-co.patch
[   76s] + exit 1
[   76s] Can't exec: Inappropriate ioctl for device
```

This is the lines in my spec:

```
Source0:        %{name}-%{version}.tar.xz
Patch0:         0001-Fix-CMakeLists-to-detect-dependencies-and-install-co.patch

...

%prep
%autosetup -p1

```

Switching to the following still produces the error:

```
%setup -q
%autopatch -p1
```

Using manual %patchN calls works, though.

**Comment by ascherer** [comment]
I wonder why `test -f` looks for the patchfile _without_ prepended `%{_sourcedir}/` (from `/usr/lib/debbuild/macros`).

**Comment by ascherer** [comment]
http://stackoverflow.com/questions/1605195/inappropriate-ioctl-for-device

**Comment by ascherer** [comment]
If a referenced patchfile does not exist in `SOURCES`, I get an empty `Can't exec:` line, but not the ioctl error. If the patchfile exists but is read-protected, I get an `Permission denied` error from `/bin/cat`, but also no ioctl error.

**Comment by Conan-Kudo** [comment]
@ascherer The patch exists in the sources, and is accessible. It works fine with `%patchN`, but not either `%autopatch` or `%autosetup`.

**Comment by ascherer** [comment]
At least in my [Stanford GraphBase specfile](https://github.com/ascherer/sgb/blob/local/sgb.spec#L39), `%autosetup -p1` works without problems.

In my [MMIX specfile](https://github.com/ascherer/mmix/blob/local/mmix.spec#L37), `%autosetup` runs fine without `-p1`, but it wouldn't hurt either:
```
-%autosetup -c %{!?with_patches:-N}
+%autosetup -c %{!?with_patches:-N}%{?with_patches:-p1}
```

As long as I can't reproduce the error, I can't search for a solution.
