### ISSUE TITLE
Inline parameterized macros do not work

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#60]
Whenever I try to use an inline parameterized macro, it doesn't successfully evaluate.

For example:

```rpm-spec
%define mkrel(c:) %{-c: 0.%{-c*}.}%{1}%{?subrel:.%subrel}%{?dist:%dist}

Release: %mkrel -c rc1 1
```

On rpm, this actually works, and `%mkrel -c rc1 1` evaluates correctly. On debbuild, it doesn't get evaluated at all and the resulting field is empty. 

It also doesn't work with `debbuild --define ... --eval ...` commands. It hangs after throwing the warning: `WARNING: missing value for macro mkrel in --define! Ignoring.` This also works in rpm. 

Interestingly, this works fine when it's defined in `/etc/debbuild/macros.mkrel` as `%mkrel(c:) %{-c: 0.%{-c*}.}%{1}%{?subrel:.%subrel}%{?dist:%dist}` and the inline definition isn't there.

Here's [RPM's documentation on macros](http://rpm.org/user_doc/macros.html) as a reference.

**Comment by ascherer** [comment]
Options of macros are stored in `%macroopts` only from configuration files at this time.

**Comment by ascherer** [comment]
Fixed in master.
