### ISSUE TITLE
RFE: Macro for setting increased verbosity

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#62]
Can a macro variable be made available for increasing verbosity by default? For build systems, it's pretty bad that debbuild isn't as verbose as rpmbuild by default, as none of that information is captured in the log.

**Comment by Conan-Kudo** [comment]
For example, I want to be able to set the equivalent of `-vv` always for OBS builds with debbuild.

**Comment by Conan-Kudo** [comment]
Nevermind, looks like it isn't needed in OBS...

**Comment by Conan-Kudo** [comment]
Erk, it is, looked at wrong log.

Here's an example of a useless log: https://build.opensuse.org/package/live_build_log/home:Pharaoh_Atem/hello/xUbuntu_16.04/x86_64

**Comment by ascherer** [comment]
Fixed in `master`. Nice idea!
