### ISSUE TITLE
debbuild should pre-evaluate globs from file lists before putting them in postinst

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#74]
An interesting surprise occurred when I used `%defattr`/`%attr` on a file list with wildcards is that it wrote that raw into a postinst, which unintentionally wound up breaking Ubuntu systems because `sudo` is a setuid binary and the bits were getting erased.

Fixing this is a matter of pre-expanding the globs and using those for the attribute/ownership setting commands.

**Comment by ascherer** [comment]
I guess all things in and around `%files` need some redesign.

**Comment by ascherer** [comment]
I was aware of this issue [some time ago](https://github.com/ascherer/debbuild/blob/master/debbuild#L1097).

Solving this doesn't look easy: The **postinst** lines are produced while scanning the specfile, way before any files are present in `%buildroot`. Globbing can occur only _after_ the **build**/**install** steps, somewhat along the lines of [manpage compaction](https://github.com/ascherer/debbuild/blob/master/debbuild#L1163).
