### ISSUE TITLE
Apply 'globbing' only in '%files' section

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#78]
On one of my packages, debbuild crashes when checking for library requirements, as seen below:

```
[  300s] Checking library requirements...
[  300s] Unmatched ) in regex; marked by <-- HERE in m/    \*) <-- HERE 
[  300s] / at /usr/bin/debbuild line 1352.
```
I'm not exactly sure what causes this, but it happens with one of my private packages all the time.

This is debbuild v17.4.3.

**Comment by Conan-Kudo** [comment]
Even when adding `AutoReq: no` to the spec, it still does it...

```
[  316s] Unmatched ) in regex; marked by <-- HERE in m/    \*) <-- HERE 
[  316s] / at /usr/bin/debbuild line 1352.
```

**Comment by Conan-Kudo** [comment]
The line in question is for the `%files` section parsing code. The `%files` list in the spec is pretty simple:

```spec
%global _webroot %{_var}/www/website
%global _nginx_confdir %{_sysconfdir}/nginx/sites-available

%files
%license dist/copyright
%{_bindir}/webctl
%{_webroot}/
%config(noreplace) %{_nginx_confdir}/website
%config(noreplace) %{_sysconfdir}/nginx/sites-enabled/website
%dir %{_var}/log/website
%dir %{_var}/log/website/logs
```

**Comment by ascherer** [comment]
I wonder why your `%files` section should invoke code line '1352' at all, as it does not contain an asterisk `*`. Most likely, the problem is related to the `%config(noreplace)` part, which is _not_ supported. I'll investigate this ASAP.

**Comment by ascherer** [comment]
I can't reproduce your issue. Copying the `%files` section AS-IS obviously doesn't work. Adding `%config(noreplace)` to one of my specfiles works without trouble (although I haven't looked into related stuff in `debbuild`, which is original 'KD').

**Comment by Conan-Kudo** [comment]
@ascherer The interesting thing is that this spec is part of a pair of spec files, both of which use `%config(noreplace)`. This one fails, but the other doesn't.

**Comment by Conan-Kudo** [comment]
@ascherer I figured out what caused it. It was my `%post` scriptlet.

```spec
%if %{_vendor} == "debbuild"
%post
case "$1" in
    configure)
    rm -f /etc/nginx/sites-enabled/default 2>/dev/null
    sed -i  -e 's/^group\ =\ www-data/group\ =\ root/g' \
            -e 's/user\ =\ www-data/user\ =\ root/g' \
                /etc/php/7.0/fpm/pool.d/www.conf

    systemctl daemon-reload
    systemctl restart php7.0-fpm
    systemctl restart nginx
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
%endif
```

**Comment by ascherer** [comment]
So I guess, globbing should _only_ occur in the `%files` section.

**Comment by Conan-Kudo** [comment]
Well, I think maybe glob processing occurred in the `%post` section to prevent #74 from happening again. Though, I'm not sure why the permissions change couldn't happen before running `dpkg-deb`, as I'm certain that it would store those correctly. I think the only issue is ownership changes, and those globs need to be pre-evaluated before being inserted into `postinst` files.

**Comment by Conan-Kudo** [comment]
Ah, I just remembered that setuid/setgid bits can't be set in the build environment and has to be applied at `postinst`. So it's quite tricky...

**Comment by ascherer** [comment]
I'll try the following:

1)  When scanning a `%files` section, do `s/\*/__GLOB__/g`
2) When actually globbing, do `unless s/__GLOB__/*/g` instead of `unless m/\*/`
