### ISSUE TITLE
Support debrc (like rpmrc) for defining optflags for various deb arches

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#84]
Currently, debbuild has the `%optflags` internalized in the script, as seen below:

https://github.com/ascherer/debbuild/blob/8358dd554c05a3b2256f2d6dc9a218813bfe0027/debbuild#L86-L92

However, RPM externalizes this to [a configuration file called `rpmrc`](https://github.com/rpm-software-management/rpm/blob/master/rpmrc.in). The `rpmrc` file can be set up such that it has macros used to fill in common parameters, and conditionals to switch on/off certain flags, as seen in [this example](https://github.com/OpenMandrivaSoftware/rpm-openmandriva-setup/blob/master/user/openmandriva/rpmrc).

Externalizing it and supporting this file will make it much easier to flexibly enable stronger compilation flags, similarly to how debian package builds can be done with optional hardening.

**Comment by ascherer** [comment]
Feature added in release 18.6.0.
