### ISSUE TITLE
Support indented conditionals

### ISSUE THREAD

**Issue by crawfxrd** [ascherer/debbuild#87]
We have a lot of nested conditions. It would make them a lot easier to read if we could indent the inner blocks. e.g.:
```
%if %{_vendor} == "debbuild"
    %if  0%{?ubuntu} && 0%{?ubuntu} < 1604
        ...
    %else
        ...
    %endif
%else
    ...
%endif
```

**Comment by ascherer** [comment]
Scheduled for the next release, but I want to consult rpm's documentation for details first.
