### ISSUE TITLE
File globs don't evaluate in build receipe

### ISSUE THREAD

**Issue by ailin-nemui** [ascherer/debbuild#95]
Log file:

```
[   73s] libtool: install: /usr/bin/install -c .libs/libpython.lai /home/abuild/debbuild/BUILDROOT/irssi-python2-test4-6.1.amd64/usr/lib/irssi/modules/libpython.la
...
[   73s] + /bin/rm /home/abuild/debbuild/BUILDROOT/irssi-python2-test4-6.1.amd64/usr/lib/irssi/modules/*.{a,la}
[   73s] /bin/rm: cannot remove '/home/abuild/debbuild/BUILDROOT/irssi-python2-test4-6.1.amd64/usr/lib/irssi/modules/*.{a,la}': No such file or directory
```

spec file:
```
%__rm %{buildroot}%{_libdir}/irssi/modules/*.{a,la}
```

**Comment by ascherer** [comment]
For more than a decade, Debian's default `/bin/sh`'ell has been [dash](https://wiki.ubuntu.com/DashAsBinSh).

If you really absolutely must use [brace expansion](https://mywiki.wooledge.org/Bashism), you'll have to switch to using 'bash':
```
debbuild --define="_buildshell /bin/bash" -bc SPECS/your.spec
```
Note that `rpmbuild` also fails with your example.

**Comment by ailin-nemui** [comment]
thanks for the answer. the same spec file works on opensuse & fedora, do you mean rpmbuild fails with dash as sh?

**Comment by ailin-nemui** [comment]
they definitely use bash. thanks very much for clearing this up to me, I'd never thought it be because of the bashism
