### ISSUE TITLE
dependencies of library are not picked up

### ISSUE THREAD

**Issue by ailin-nemui** [ascherer/debbuild#97]
hi, do you have some idea why no dependencies are picked up here:

https://build.opensuse.org/package/show/home:ailin_nemui:testtest/irssi-robustirc

https://download.opensuse.org/repositories/home:/ailin_nemui:/testtest/Debian_9.0/i386/irssi-robustirc_0.6+5+g6c0b51c-12.1_i386.deb

```
ldd /usr/lib/irssi/modules/librobustirc_core.so 
...
        libyajl.so.2 => not found
        libcurl.so.4 => not found
...
```

needs libyajl2 and libcurl3

**Comment by ascherer** [comment]
No, I can't help right now, because (K)Ubuntu doesn't provide the following `BuildRequires:`:
```
Statusinformationen werden eingelesen.... Fertig
E: Paket irssi-git-devel kann nicht gefunden werden.
E: Paket glib2-devel kann nicht gefunden werden.
E: Paket libyajl-devel kann nicht gefunden werden.
E: Paket libcurl-devel kann nicht gefunden werden.
E: Paket gcc-c+ kann nicht gefunden werden.
E: Mittels regulärem Ausdruck »gcc-c+« konnte kein Paket gefunden werden.
E: Paket pkgconfig kann nicht gefunden werden.
```

**Comment by ailin-nemui** [comment]
thanks for helping. try adding %ubuntu_version 1604 to your macros

**Comment by ailin-nemui** [comment]
still you would likely need to build or download the irssi-git package from the same repo

**Comment by ascherer** [comment]
`irssi-git-dev` for Debian 9.0 requires at least`perl >= 5.24`, but Kubuntu 16.04 has Perl 5.22, `irssi-git-dev` for Debian 8.0 requires exact version `perl = 5.20`. I'm stymied.

**Comment by ailin-nemui** [comment]
hi, I added ubuntu 16.04 I hope that makes it easier for you to help me (and sorry it was not available right away!) 

https://download.opensuse.org/repositories/home:/ailin_nemui:/testtest/Ubuntu_16.04/

**Comment by ascherer** [comment]
Could you please modify the version requirement for Perl?
```
irssi-git hängt ab von perl (= 5.22.1-9); aber:
  Version von perl auf dem System ist 5.22.1-9ubuntu0.5.
```
`=` is too strict.

**Comment by ailin-nemui** [comment]
should be fixed now!

**Comment by ascherer** [comment]
Minor suggestion for your specfile:
```
diff --git a/SPECS/irssi-robustirc.spec b/SPECS/irssi-robustirc.spec
index 0928c63..abf0b72 100644
--- a/SPECS/irssi-robustirc.spec
+++ b/SPECS/irssi-robustirc.spec
@@ -58,8 +58,8 @@ cmake \
 %if "%{?_lib}" == "lib64" 
         -DLIB_SUFFIX=64 \
 %endif 
-        ..
-make %{?_smp_mflags}
+cd ..
+%{_make_build}
 
 
 %install
```

**Comment by ascherer** [comment]
I think I found the cause of this issue. It seems that `%make_install -C Build` strips the executable flags of the two `.so` files.

If I `tree BUILD/irssi-robustirc-master/` all is fine, but when I `tree BUILDROOT/irssi-robustirc-0.6+5+g6c0b51c-0.amd64/`, all `modules` only have `644`  instead of `755` (you'll probably have to use the `--noclean` option to keep this). This aborts the ` Checking library requirements...` step prior to actually packaging.

I'm totally unfamiliar with `cmake`, so I'll hand this back to you to investigate.

**Comment by ailin-nemui** [comment]
d'oh. why, cmake. (I am also not too much familiar with it...)
thank you so much!

for the reference a 
```
        -DCMAKE_INSTALL_SO_NO_EXE=0
```
in my %build cmake command fixes it.
